# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: SpacyNLP
    model: "en_core_web_sm"
  - name: SpacyTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: SpacyEntityExtractor
    dimensions: ["GPE", "PRODUCT"]
  - name: DIETClassifier
    epochs: 100
    BILOU_flag: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: FormPolicy
  - name: MappingPolicy
  - name: MemoizationPolicy
    max_history: 6
  - name: TEDPolicy
    max_history: 10
    epochs: 100
  - name: FallbackPolicy
    nlu_threshold: 0.50
    fallback_action_name: 'action_custom_fallback'
    